version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: passgen
      MYSQL_USER: passgen
      MYSQL_PASSWORD: passgen
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      #MYSQL_ROOT_PASSWORD: 78964254
    ports:
      - 3306:3306
    volumes:
      - mysql_docker:/var/lib/mysql

volumes:
  mysql_docker:
